name = "Roblox Deletion Queue"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[observability.logs]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "rdq-database"                       # database name
database_id = "a873ca8b-15a3-406c-952e-cf948a152130" # database id  